# Generated by Django 3.0.5 on 2020-04-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200417_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
