# Generated by Django 3.0.5 on 2020-04-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_view_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='view_counter',
        ),
        migrations.AddField(
            model_name='post',
            name='views_counter',
            field=models.IntegerField(default=0),
        ),
    ]
