# Generated by Django 3.0.5 on 2020-04-23 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20200418_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='board',
        ),
    ]
